export type PilotVerticalBounds = {
	bottom: number
	top: number
}

export const PILOT_MODEL_SCALE = 0.54

export const PILOT_RIG_STANDING_HIPS_HEIGHT = 1.72
export const PILOT_RIG_TORSO_SHELL_HEIGHT = 0.8
export const PILOT_RIG_TORSO_PLATE_OFFSET_Y = 0.14
export const PILOT_RIG_TORSO_CENTER_Y =
	PILOT_RIG_TORSO_SHELL_HEIGHT + PILOT_RIG_TORSO_PLATE_OFFSET_Y
export const PILOT_RIG_TORSO_CENTER_Z = -0.03
export const PILOT_RIG_TORSO_HALF_HEIGHT = 0.72 / 2
export const PILOT_RIG_TORSO_HALF_DEPTH = 0.72 / 2

export const PILOT_RIG_NECK_HEIGHT = 1.45
export const PILOT_RIG_HEAD_OFFSET = 0.29
export const PILOT_RIG_HELMET_HALF_HEIGHT = 0.48 * 0.96
export const PILOT_RIG_HELMET_HALF_DEPTH = 0.48 * 1.08

export const PILOT_CROUCH_ROOT_OFFSET = -0.5
export const PILOT_CROUCH_HIPS_HEIGHT = 1.52
export const PILOT_CROUCH_BODY_OFFSET = -0.06
export const PILOT_CROUCH_BODY_PITCH = -0.52
export const PILOT_CROUCH_NECK_PITCH = -0.05
export const PILOT_CROUCH_HEAD_PITCH = -0.07

function verticalHalfExtent(
	halfHeight: number,
	halfDepth: number,
	pitch: number,
): number {
	return (
		Math.abs(Math.cos(pitch)) * halfHeight +
		Math.abs(Math.sin(pitch)) * halfDepth
	)
}

function bounds(center: number, halfExtent: number): PilotVerticalBounds {
	return { bottom: center - halfExtent, top: center + halfExtent }
}

export const PILOT_STANDING_TORSO_CENTER_HEIGHT =
	(PILOT_RIG_STANDING_HIPS_HEIGHT + PILOT_RIG_TORSO_CENTER_Y) *
	PILOT_MODEL_SCALE
export const PILOT_STANDING_TORSO_BOUNDS = bounds(
	PILOT_STANDING_TORSO_CENTER_HEIGHT,
	PILOT_RIG_TORSO_HALF_HEIGHT * PILOT_MODEL_SCALE,
)

const crouchedTorsoCenterInRig =
	PILOT_CROUCH_HIPS_HEIGHT +
	PILOT_CROUCH_BODY_OFFSET +
	Math.cos(PILOT_CROUCH_BODY_PITCH) * PILOT_RIG_TORSO_CENTER_Y -
	Math.sin(PILOT_CROUCH_BODY_PITCH) * PILOT_RIG_TORSO_CENTER_Z
export const PILOT_CROUCH_TORSO_CENTER_HEIGHT =
	PILOT_CROUCH_ROOT_OFFSET + crouchedTorsoCenterInRig * PILOT_MODEL_SCALE
export const PILOT_CROUCH_TORSO_BOUNDS = bounds(
	PILOT_CROUCH_TORSO_CENTER_HEIGHT,
	verticalHalfExtent(
		PILOT_RIG_TORSO_HALF_HEIGHT,
		PILOT_RIG_TORSO_HALF_DEPTH,
		PILOT_CROUCH_BODY_PITCH,
	) * PILOT_MODEL_SCALE,
)

export const PILOT_STANDING_HEAD_CENTER_HEIGHT =
	(PILOT_RIG_STANDING_HIPS_HEIGHT +
		PILOT_RIG_NECK_HEIGHT +
		PILOT_RIG_HEAD_OFFSET) *
	PILOT_MODEL_SCALE
export const PILOT_STANDING_HEAD_BOUNDS = bounds(
	PILOT_STANDING_HEAD_CENTER_HEIGHT,
	PILOT_RIG_HELMET_HALF_HEIGHT * PILOT_MODEL_SCALE,
)

const crouchedHeadCenterInRig =
	PILOT_CROUCH_HIPS_HEIGHT +
	PILOT_CROUCH_BODY_OFFSET +
	Math.cos(PILOT_CROUCH_BODY_PITCH) * PILOT_RIG_NECK_HEIGHT +
	Math.cos(PILOT_CROUCH_BODY_PITCH + PILOT_CROUCH_NECK_PITCH) *
		PILOT_RIG_HEAD_OFFSET
export const PILOT_CROUCH_HEAD_CENTER_HEIGHT =
	PILOT_CROUCH_ROOT_OFFSET + crouchedHeadCenterInRig * PILOT_MODEL_SCALE
export const PILOT_CROUCH_HEAD_BOUNDS = bounds(
	PILOT_CROUCH_HEAD_CENTER_HEIGHT,
	verticalHalfExtent(
		PILOT_RIG_HELMET_HALF_HEIGHT,
		PILOT_RIG_HELMET_HALF_DEPTH,
		PILOT_CROUCH_BODY_PITCH + PILOT_CROUCH_NECK_PITCH + PILOT_CROUCH_HEAD_PITCH,
	) * PILOT_MODEL_SCALE,
)

export const PILOT_HEAD_HIT_RADIUS =
	Math.max(PILOT_RIG_HELMET_HALF_HEIGHT, PILOT_RIG_HELMET_HALF_DEPTH) *
	PILOT_MODEL_SCALE

export const PILOT_STANDING_BODY_HIT_BOUNDS: PilotVerticalBounds = {
	bottom: 0.45,
	top: PILOT_STANDING_TORSO_BOUNDS.top,
}
export const PILOT_CROUCH_BODY_HIT_BOUNDS: PilotVerticalBounds = {
	bottom: 0.4,
	top: PILOT_CROUCH_TORSO_BOUNDS.top,
}
